# This is a basic workflow to help you get started with Actions

name: bi-monthly update

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
    push:
      branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: install dependencies
        run: pip install --upgrade -r requirements.txt

      
      - name: run script
        run: |
          git pull
          rm html/*.html 
          #rm image/*.jpg 
          #rm image/*.png
          python fetchFA.py
        
      - name: git push
        run: |
          git add .
          git config --global user.name "Taizi Huang"
          git config --global user.email "htzllt@gmail.com"
          git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')" --allow-empty
          git push
